language: node_js
node_js:
- '8'
branches:
  only:
  - master
  - develop
  - "/snyk-*/"
deploy:
  provider: heroku
  api_key:
    secure: hMjLA1y4Zp23DE0v4JJBIXEwbqACfuTgQRLNI+LHv0HRlemcAdu7ZBpPSunwFqDaoVqxC5S1s7fnInOdpfjw0vmA2eXNTMxEgFlHmVm0XXqCs4Rn3ZSAGZdTfQ6KQYwEEQnk54Rw4c71ugUUPhxXa+HTzTDdYTPKxfiom6D3n6pWxvXvIRVMWBrYJcCnbf+2jYLdIg/ekbfqal1ucIyTPLUXEdgtNQZ+5nAG4UzMd2X72szOQV5ubqNQmT/jTgbea1lZxcbgytj+4DXtGL2+hQ2wmoByEqEYDoW9GxEjiCXU4hIJkuZ1etk0Lx5pjYHtJ75G/0TmTwXkN8cC1HoEf3VKlZyYyxukh18ikc7LFUkOvxVCyXTsJpZPN8PvC0BhQPUBLpmSAvHVXGBKsEBQu8OkPCkC3Ws2DpW1zy/PWpqQOf4J9Mu4PFq6xbGMwWueWE0QWCM9RM3vnHj0diCGjCRrcFiJDp1s+pug3Eyn4ZOUWuwsSatIhjLMj9FjuhYmwjlou5NSe3sH0c/PTjO2tMp+DkzB2oZiRSMkFnfLeI/XNSxFCgmYNl1MdnT/vn3WcQGMFEUmM12O8ofj1DbdkAZWqwWG7xtYXeJW0AhE8CP4AmrGYrscIjwrGxgON3XB0r7iqMmlyKkJtk5Y5Ha1/k3jjUWcR+NRe4mJbfvPY5I=
  app:
    master: spotifysidekick
notifications:
  slack:
    secure: vs0l2bbXKtoajqvAog4WdpqDIfb5420ys9w5tUzYx0ay6Sg5/jeOVrJPCntQUkoptxlOcHdmGuqeUex4MzkzcNKzT9+Sp0ChjuUEeXn735tPQKCibaaNU+gEg796LFbVq3AQxmiRTl+sBCU0GzThdJAb6XGCwlUemvTJfptnQsyZ9+iJDQNWZAlP7ZYesDImEobEynVRz220UZrZALzKqxAYVYCVehnNfiZzVcHIXk8v8y5PZkD7tCvvYtQ5It1dEEIstFz1ZwKxq//hx9gvfltdmuY58wqGRZeQgNITv+HCR2n4tVTmWA7Sy80fYn4nlxbyqY6GA/qExaKbb7qcoi2LC1XZpAfdeEvUJvmhd5dX4fhlPo7pz5ZYKLT+AcNxQ2n5PrOnRS6A1hU6Up/ib4PEjNZ/j+nNG+7ft+k10fycm+eKXfQLaM6ff9ORU8F4L+9GrD/w7RXKSaVKIz8WkZ7jm5XIhXeNo5vRVWG2eRewn0yceQGww35AShs0qW1U32RrsSFZms+ggJ3C5l/1Fhr4pJH9DRx3H5C+9/3XliLJTgkdV2iGw1kN3w3N1Ve3IMnsog9WFZxkBuCAOSHQ+0wIZMlQHjzC1tPltmUg92Pv1K33iNf0js3itgKNZGfO2PYcKdCEGd8ciz9IeDqFRjWRkh418H/Szzk0A57CFDo=
